// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_7NB13R38TgoBIXco4ghyqxlYvLHHj2U',
    appId: '1:551428521121:web:193aca2f1811e5e73a84e0',
    messagingSenderId: '551428521121',
    projectId: 'travel-guide-app-b7539',
    authDomain: 'travel-guide-app-b7539.firebaseapp.com',
    storageBucket: 'travel-guide-app-b7539.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl4u4c_Z8UrIJvD1DSHmzWe6J_E05kN1w',
    appId: '1:551428521121:android:27229028301e2d333a84e0',
    messagingSenderId: '551428521121',
    projectId: 'travel-guide-app-b7539',
    storageBucket: 'travel-guide-app-b7539.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClki_Nh5inu7CwEh8brDVaXfbwoqdY-JA',
    appId: '1:551428521121:ios:e74f9806f49bab993a84e0',
    messagingSenderId: '551428521121',
    projectId: 'travel-guide-app-b7539',
    storageBucket: 'travel-guide-app-b7539.firebasestorage.app',
    iosBundleId: 'com.example.travelGuideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClki_Nh5inu7CwEh8brDVaXfbwoqdY-JA',
    appId: '1:551428521121:ios:e74f9806f49bab993a84e0',
    messagingSenderId: '551428521121',
    projectId: 'travel-guide-app-b7539',
    storageBucket: 'travel-guide-app-b7539.firebasestorage.app',
    iosBundleId: 'com.example.travelGuideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_7NB13R38TgoBIXco4ghyqxlYvLHHj2U',
    appId: '1:551428521121:web:cbce7fd101870c033a84e0',
    messagingSenderId: '551428521121',
    projectId: 'travel-guide-app-b7539',
    authDomain: 'travel-guide-app-b7539.firebaseapp.com',
    storageBucket: 'travel-guide-app-b7539.firebasestorage.app',
  );
}
